In [17]:
import pandas as pd
import pickle
from tensorflow.keras.models import load_model
import numpy as np

In [18]:
model = load_model('model.h5')

with open('scaler.pkl', 'rb') as f:
    scaler = pickle.load(f)
with open('label_encoder_gender.pkl', 'rb') as f:
    label_encoder = pickle.load(f)  
with open('one_hot_encoder_geo.pkl', 'rb') as f:
    onehot_encoder = pickle.load(f)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [25]:
input_data = {
    'CreditScore':700,
    'Geography':'France',
    'Gender':'Male',
    'Age':40,
    'Tenure':3,
    'Balance':60000,
    'NumOfProducts':2,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':50000
}

In [26]:
geo_encoded = onehot_encoder.transform([[input_data['Geography']]]).toarray()
geo_df = pd.DataFrame(geo_encoded, columns = onehot_encoder.get_feature_names_out(['Geography']))

x:\ML\classification_project\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [27]:
input_df = pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,700,France,Male,40,3,60000,2,1,1,50000

In [28]:
#Encode categorical variables
input_df['Gender'] = label_encoder.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,700,France,1,40,3,60000,2,1,1,50000

In [29]:
input_df = pd.concat([input_df.drop('Geography', axis=1), geo_df], axis=1)

In [30]:
input_df
input_scaled = scaler.transform(input_df)

In [32]:
prediction = model.predict(input_scaled)
prediction = (prediction > 0.5).astype(int)
print("Predicted class:", prediction[0][0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
Predicted class: 0